/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChangePasswordRouteImport } from './routes/change-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUtilisateursRouteImport } from './routes/_authenticated/utilisateurs'
import { Route as AuthenticatedSequencesRouteImport } from './routes/_authenticated/sequences'
import { Route as AuthenticatedRessourcesRouteImport } from './routes/_authenticated/ressources'
import { Route as AuthenticatedRecapitulatifRouteImport } from './routes/_authenticated/recapitulatif'
import { Route as AuthenticatedFicheEnseignantRouteImport } from './routes/_authenticated/fiche-enseignant'
import { Route as AuthenticatedEtatsPaiementRouteImport } from './routes/_authenticated/etats-paiement'
import { Route as AuthenticatedEtatsGlobauxRouteImport } from './routes/_authenticated/etats-globaux'
import { Route as AuthenticatedEnseignantsRouteImport } from './routes/_authenticated/enseignants'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoursRouteImport } from './routes/_authenticated/cours'
import { Route as AuthenticatedBaremesRouteImport } from './routes/_authenticated/baremes'
import { Route as AuthenticatedAnneesAcademiquesRouteImport } from './routes/_authenticated/annees-academiques'
import { Route as AuthenticatedActivitesRouteImport } from './routes/_authenticated/activites'

const ChangePasswordRoute = ChangePasswordRouteImport.update({
  id: '/change-password',
  path: '/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUtilisateursRoute =
  AuthenticatedUtilisateursRouteImport.update({
    id: '/utilisateurs',
    path: '/utilisateurs',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSequencesRoute = AuthenticatedSequencesRouteImport.update({
  id: '/sequences',
  path: '/sequences',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRessourcesRoute = AuthenticatedRessourcesRouteImport.update({
  id: '/ressources',
  path: '/ressources',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRecapitulatifRoute =
  AuthenticatedRecapitulatifRouteImport.update({
    id: '/recapitulatif',
    path: '/recapitulatif',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFicheEnseignantRoute =
  AuthenticatedFicheEnseignantRouteImport.update({
    id: '/fiche-enseignant',
    path: '/fiche-enseignant',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEtatsPaiementRoute =
  AuthenticatedEtatsPaiementRouteImport.update({
    id: '/etats-paiement',
    path: '/etats-paiement',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEtatsGlobauxRoute =
  AuthenticatedEtatsGlobauxRouteImport.update({
    id: '/etats-globaux',
    path: '/etats-globaux',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEnseignantsRoute =
  AuthenticatedEnseignantsRouteImport.update({
    id: '/enseignants',
    path: '/enseignants',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoursRoute = AuthenticatedCoursRouteImport.update({
  id: '/cours',
  path: '/cours',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedBaremesRoute = AuthenticatedBaremesRouteImport.update({
  id: '/baremes',
  path: '/baremes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAnneesAcademiquesRoute =
  AuthenticatedAnneesAcademiquesRouteImport.update({
    id: '/annees-academiques',
    path: '/annees-academiques',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedActivitesRoute = AuthenticatedActivitesRouteImport.update({
  id: '/activites',
  path: '/activites',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/activites': typeof AuthenticatedActivitesRoute
  '/annees-academiques': typeof AuthenticatedAnneesAcademiquesRoute
  '/baremes': typeof AuthenticatedBaremesRoute
  '/cours': typeof AuthenticatedCoursRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/enseignants': typeof AuthenticatedEnseignantsRoute
  '/etats-globaux': typeof AuthenticatedEtatsGlobauxRoute
  '/etats-paiement': typeof AuthenticatedEtatsPaiementRoute
  '/fiche-enseignant': typeof AuthenticatedFicheEnseignantRoute
  '/recapitulatif': typeof AuthenticatedRecapitulatifRoute
  '/ressources': typeof AuthenticatedRessourcesRoute
  '/sequences': typeof AuthenticatedSequencesRoute
  '/utilisateurs': typeof AuthenticatedUtilisateursRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/activites': typeof AuthenticatedActivitesRoute
  '/annees-academiques': typeof AuthenticatedAnneesAcademiquesRoute
  '/baremes': typeof AuthenticatedBaremesRoute
  '/cours': typeof AuthenticatedCoursRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/enseignants': typeof AuthenticatedEnseignantsRoute
  '/etats-globaux': typeof AuthenticatedEtatsGlobauxRoute
  '/etats-paiement': typeof AuthenticatedEtatsPaiementRoute
  '/fiche-enseignant': typeof AuthenticatedFicheEnseignantRoute
  '/recapitulatif': typeof AuthenticatedRecapitulatifRoute
  '/ressources': typeof AuthenticatedRessourcesRoute
  '/sequences': typeof AuthenticatedSequencesRoute
  '/utilisateurs': typeof AuthenticatedUtilisateursRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/change-password': typeof ChangePasswordRoute
  '/_authenticated/activites': typeof AuthenticatedActivitesRoute
  '/_authenticated/annees-academiques': typeof AuthenticatedAnneesAcademiquesRoute
  '/_authenticated/baremes': typeof AuthenticatedBaremesRoute
  '/_authenticated/cours': typeof AuthenticatedCoursRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/enseignants': typeof AuthenticatedEnseignantsRoute
  '/_authenticated/etats-globaux': typeof AuthenticatedEtatsGlobauxRoute
  '/_authenticated/etats-paiement': typeof AuthenticatedEtatsPaiementRoute
  '/_authenticated/fiche-enseignant': typeof AuthenticatedFicheEnseignantRoute
  '/_authenticated/recapitulatif': typeof AuthenticatedRecapitulatifRoute
  '/_authenticated/ressources': typeof AuthenticatedRessourcesRoute
  '/_authenticated/sequences': typeof AuthenticatedSequencesRoute
  '/_authenticated/utilisateurs': typeof AuthenticatedUtilisateursRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/change-password'
    | '/activites'
    | '/annees-academiques'
    | '/baremes'
    | '/cours'
    | '/dashboard'
    | '/enseignants'
    | '/etats-globaux'
    | '/etats-paiement'
    | '/fiche-enseignant'
    | '/recapitulatif'
    | '/ressources'
    | '/sequences'
    | '/utilisateurs'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/change-password'
    | '/activites'
    | '/annees-academiques'
    | '/baremes'
    | '/cours'
    | '/dashboard'
    | '/enseignants'
    | '/etats-globaux'
    | '/etats-paiement'
    | '/fiche-enseignant'
    | '/recapitulatif'
    | '/ressources'
    | '/sequences'
    | '/utilisateurs'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/change-password'
    | '/_authenticated/activites'
    | '/_authenticated/annees-academiques'
    | '/_authenticated/baremes'
    | '/_authenticated/cours'
    | '/_authenticated/dashboard'
    | '/_authenticated/enseignants'
    | '/_authenticated/etats-globaux'
    | '/_authenticated/etats-paiement'
    | '/_authenticated/fiche-enseignant'
    | '/_authenticated/recapitulatif'
    | '/_authenticated/ressources'
    | '/_authenticated/sequences'
    | '/_authenticated/utilisateurs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ChangePasswordRoute: typeof ChangePasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/change-password': {
      id: '/change-password'
      path: '/change-password'
      fullPath: '/change-password'
      preLoaderRoute: typeof ChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/utilisateurs': {
      id: '/_authenticated/utilisateurs'
      path: '/utilisateurs'
      fullPath: '/utilisateurs'
      preLoaderRoute: typeof AuthenticatedUtilisateursRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/sequences': {
      id: '/_authenticated/sequences'
      path: '/sequences'
      fullPath: '/sequences'
      preLoaderRoute: typeof AuthenticatedSequencesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/ressources': {
      id: '/_authenticated/ressources'
      path: '/ressources'
      fullPath: '/ressources'
      preLoaderRoute: typeof AuthenticatedRessourcesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/recapitulatif': {
      id: '/_authenticated/recapitulatif'
      path: '/recapitulatif'
      fullPath: '/recapitulatif'
      preLoaderRoute: typeof AuthenticatedRecapitulatifRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/fiche-enseignant': {
      id: '/_authenticated/fiche-enseignant'
      path: '/fiche-enseignant'
      fullPath: '/fiche-enseignant'
      preLoaderRoute: typeof AuthenticatedFicheEnseignantRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/etats-paiement': {
      id: '/_authenticated/etats-paiement'
      path: '/etats-paiement'
      fullPath: '/etats-paiement'
      preLoaderRoute: typeof AuthenticatedEtatsPaiementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/etats-globaux': {
      id: '/_authenticated/etats-globaux'
      path: '/etats-globaux'
      fullPath: '/etats-globaux'
      preLoaderRoute: typeof AuthenticatedEtatsGlobauxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/enseignants': {
      id: '/_authenticated/enseignants'
      path: '/enseignants'
      fullPath: '/enseignants'
      preLoaderRoute: typeof AuthenticatedEnseignantsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cours': {
      id: '/_authenticated/cours'
      path: '/cours'
      fullPath: '/cours'
      preLoaderRoute: typeof AuthenticatedCoursRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/baremes': {
      id: '/_authenticated/baremes'
      path: '/baremes'
      fullPath: '/baremes'
      preLoaderRoute: typeof AuthenticatedBaremesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/annees-academiques': {
      id: '/_authenticated/annees-academiques'
      path: '/annees-academiques'
      fullPath: '/annees-academiques'
      preLoaderRoute: typeof AuthenticatedAnneesAcademiquesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/activites': {
      id: '/_authenticated/activites'
      path: '/activites'
      fullPath: '/activites'
      preLoaderRoute: typeof AuthenticatedActivitesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedActivitesRoute: typeof AuthenticatedActivitesRoute
  AuthenticatedAnneesAcademiquesRoute: typeof AuthenticatedAnneesAcademiquesRoute
  AuthenticatedBaremesRoute: typeof AuthenticatedBaremesRoute
  AuthenticatedCoursRoute: typeof AuthenticatedCoursRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEnseignantsRoute: typeof AuthenticatedEnseignantsRoute
  AuthenticatedEtatsGlobauxRoute: typeof AuthenticatedEtatsGlobauxRoute
  AuthenticatedEtatsPaiementRoute: typeof AuthenticatedEtatsPaiementRoute
  AuthenticatedFicheEnseignantRoute: typeof AuthenticatedFicheEnseignantRoute
  AuthenticatedRecapitulatifRoute: typeof AuthenticatedRecapitulatifRoute
  AuthenticatedRessourcesRoute: typeof AuthenticatedRessourcesRoute
  AuthenticatedSequencesRoute: typeof AuthenticatedSequencesRoute
  AuthenticatedUtilisateursRoute: typeof AuthenticatedUtilisateursRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedActivitesRoute: AuthenticatedActivitesRoute,
  AuthenticatedAnneesAcademiquesRoute: AuthenticatedAnneesAcademiquesRoute,
  AuthenticatedBaremesRoute: AuthenticatedBaremesRoute,
  AuthenticatedCoursRoute: AuthenticatedCoursRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEnseignantsRoute: AuthenticatedEnseignantsRoute,
  AuthenticatedEtatsGlobauxRoute: AuthenticatedEtatsGlobauxRoute,
  AuthenticatedEtatsPaiementRoute: AuthenticatedEtatsPaiementRoute,
  AuthenticatedFicheEnseignantRoute: AuthenticatedFicheEnseignantRoute,
  AuthenticatedRecapitulatifRoute: AuthenticatedRecapitulatifRoute,
  AuthenticatedRessourcesRoute: AuthenticatedRessourcesRoute,
  AuthenticatedSequencesRoute: AuthenticatedSequencesRoute,
  AuthenticatedUtilisateursRoute: AuthenticatedUtilisateursRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ChangePasswordRoute: ChangePasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
